### LAZY METHOD <hr>

In [41]:
import torch
import torch.nn as nn

In [42]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)
    
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

In [43]:
model = Model(n_input_features=6)
### train your model

In [44]:
FILE = "model.pth"
torch.save(model, FILE)

In [45]:
loaded_model = torch.load(FILE)
loaded_model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [46]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.3190,  0.1579,  0.2236,  0.0318, -0.2505,  0.3876]],
       requires_grad=True)
Parameter containing:
tensor([0.3049], requires_grad=True)


### Recommended Method <hr>

In [47]:
model2 = Model(n_input_features=4)
### train your model

In [48]:
FILE = "model2.pth"
torch.save(model2.state_dict(), FILE)

In [49]:
loaded_model2 = Model(n_input_features=4)
loaded_model2.load_state_dict(torch.load(FILE))
loaded_model2.eval()

Model(
  (linear): Linear(in_features=4, out_features=1, bias=True)
)

In [50]:
for param in loaded_model2.parameters():
    print(param)

Parameter containing:
tensor([[-0.1210,  0.2981, -0.3846,  0.3367]], requires_grad=True)
Parameter containing:
tensor([-0.4512], requires_grad=True)


In [51]:
print(model2.state_dict())

OrderedDict({'linear.weight': tensor([[-0.1210,  0.2981, -0.3846,  0.3367]]), 'linear.bias': tensor([-0.4512])})


### Saving Checkpoint <hr>

In [52]:
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [53]:
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


In [54]:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "opim_state": optimizer.state_dict()
}

In [55]:
torch.save(checkpoint, "checkpoint.pth")

In [56]:
loaded_checkpoint = torch.load("checkpoint.pth")
print(loaded_checkpoint)

{'epoch': 90, 'model_state': OrderedDict({'linear.weight': tensor([[ 0.3190,  0.1579,  0.2236,  0.0318, -0.2505,  0.3876]]), 'linear.bias': tensor([0.3049])}), 'opim_state': {'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}}


In [57]:
epoch = loaded_checkpoint["epoch"]
model = Model(n_input_features=6)
optimizer = torch.optim.SGD(model.parameters(), lr=0)

In [58]:
model.load_state_dict(checkpoint["model_state"])
optimizer.load_state_dict(checkpoint["opim_state"])

In [59]:
print(model)

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)


In [60]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


### Save on GPU, Load on CPU <hr>

In [61]:
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), FILE)

In [62]:
device = torch.device("cpu")
model = Model(n_input_features=6)
model.load_state_dict(torch.load(FILE, map_location=device))

<All keys matched successfully>

### Save on GPU, Load on GPU <hr>

In [63]:
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), FILE)

In [64]:
model = Model(n_input_features=6)
model.load_state_dict(torch.load(FILE))
model.to(device)

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

### Save on CPU, Load on GPU <hr>

In [65]:
torch.save(model.state_dict(), FILE)

In [66]:
model = torch.device("cuda")
model = Model(n_input_features=6)
model.load_state_dict(torch.load(FILE, map_location="cuda:0"))
model.to(device)

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)