In [48]:
import torch
import numpy as np

In [49]:
x = torch.empty(1)
print(x)

tensor([-2.7033e+16])


In [50]:
x = torch.empty(3)
print(x)

tensor([0.0000e+00, 2.1601e+02, 2.3694e-38])


In [51]:
x = torch.empty(2,3)
print(x)

tensor([[0.5577, 0.9864, 0.6132],
        [0.2228, 0.3685, 0.0000]])


In [52]:
x = torch.rand(2,2)
print(x)

tensor([[0.7674, 0.4179],
        [0.2117, 0.4464]])


In [53]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [54]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [55]:
x.dtype

torch.float32

In [56]:
x = torch.ones(2,2, dtype=torch.int)
#torch.int
#torch.double
#torch.float16

In [57]:
x.size()

torch.Size([2, 2])

In [58]:
#from a python list
x = torch.tensor([2.3, 0.12])
print(x)

tensor([2.3000, 0.1200])


In [59]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y # z = torch.add(x,y)
print(f"Element wise addition: {z}")

tensor([[0.4656, 0.2333],
        [0.8585, 0.2206]])
tensor([[0.4668, 0.5945],
        [0.9917, 0.2813]])
Element wise addition: tensor([[0.9324, 0.8278],
        [1.8503, 0.5018]])


In [60]:
#inplace operations
#in pytorch functions with "_" will do in inplace operation
y.add_(x)
print("Inplace Addition: ", y)

Inplace Addition:  tensor([[0.9324, 0.8278],
        [1.8503, 0.5018]])


In [61]:
#element wise operations

torch.add(x,y)
torch.sub(x,y)
torch.mul(x,y) #element wise multiplication
torch.div(x,y) #element wise division

tensor([[0.4993, 0.2819],
        [0.4640, 0.4395]])

In [62]:
#slicing operation
x = torch.rand(5,3)
print(x)

print(x[:, 0]) #prints the first column
print(x[1, :]) #prints the second row
print(x[1, 2]) #prints the value but in tensor
print(x[1, 2].item()) #prints the value as scalar

tensor([[0.0333, 0.7525, 0.0883],
        [0.9197, 0.9148, 0.5531],
        [0.8502, 0.2410, 0.8930],
        [0.9375, 0.4106, 0.4691],
        [0.1301, 0.8408, 0.5318]])
tensor([0.0333, 0.9197, 0.8502, 0.9375, 0.1301])
tensor([0.9197, 0.9148, 0.5531])
tensor(0.5531)
0.5531076192855835


In [63]:
#reshaping or resizing
x = torch.rand(4,4)
print(x.size())

y = x.view(16)
print(y.size())
y = x.view(-1, 8)
print(y.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [69]:
#np to tensor and vice-versa
a = torch.ones(5)
print(type(a))
b = a.numpy()
print(type(b))

a.add_(1)
print(a, b)
#both of them changed because they both point to the same memory location

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [75]:
a = np.ones(5)
print(type(a))
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [79]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("cuda available")

cuda available


In [85]:
x = torch.ones(5, device = device)
y = torch.ones(5)
y = y.to(device)
z = x + y

#as numpy cannot handle GPU locations
# b = z.numpy() , this will give error

a = z.to("cpu")
b = z.to("cpu").numpy()

z.add_(1)
print(z)
print(b)

#as both are on different devices, they no longer share the same memory locations


tensor([3., 3., 3., 3., 3.], device='cuda:0')
[2. 2. 2. 2. 2.]


In [86]:
x = torch.ones(5, requires_grad=True)
#by default requires_grad is False
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
