## Tensor Basics

In [145]:
import tensorflow as tf

### Initialization of Tensors

In [146]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [147]:
x = tf.constant(4.0, shape=(1,1))
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [148]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [149]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [150]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [151]:
x = tf.eye(3) # identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [152]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-1.1736966  -0.61550206  0.50354743]
 [ 0.42995834 -2.8349042   0.8352035 ]
 [-0.17047064  0.49549273 -0.31273398]], shape=(3, 3), dtype=float32)


In [153]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.5142236  0.36222482 0.6611903 ]], shape=(1, 3), dtype=float32)


In [154]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [155]:
x = tf.range(start=1, limit=10, delta=3)
print(x)

tf.Tensor([1 4 7], shape=(3,), dtype=int32)


### Cast in TensorFlow

In [156]:
x = tf.cast(x, dtype=tf.float32)
# tf.float (16, 32, 64) 
# tf.int (8, 16, 32, 64)
# tf.bool
print(x)

tf.Tensor([1. 4. 7.], shape=(3,), dtype=float32)


### Mathematical Operations

In [157]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
print(x)
print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [158]:
# element wise addition
z = tf.add(x, y)
z = x + y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [159]:
# element wise subtraction
z = tf.subtract(x, y)
z = x - y
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [160]:
# element wise division
z = tf.divide(x, y)
z = x / y
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [161]:
# element wise multiplication
z = tf.multiply(x, y)
z = x * y
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [162]:
# dot product
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [163]:
# dot product equivalent
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [164]:
# element wise exponentiation
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [165]:
# matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x, y)
z = x @ y

print(z)

tf.Tensor(
[[ 0.55304694  0.17557782 -0.94148076  0.8769022 ]
 [-1.2828712  -0.30248976  1.1643709   0.35584998]], shape=(2, 4), dtype=float32)


### Indexing

In [166]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [167]:
# slicing is [inclusive:non-inclusive] 
print(x[:])

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [168]:
print(x[2:])

tf.Tensor([2 3 4 5 6 7 8], shape=(7,), dtype=int32)


In [169]:
print(x[2:6])

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [170]:
# skip every other element
print(x[::2])
print(x[::3])

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([0 3 6], shape=(3,), dtype=int32)


In [171]:
# reverse the order
print(x[::-1])

tf.Tensor([8 7 6 5 4 3 2 1 0], shape=(9,), dtype=int32)


In [172]:
# get specific indices from a tensor
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [173]:
x = tf.constant([[1,2],
                [3,4],
                [5,6]])
# 1st row and all columns
print(x[0, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)


### Reshaping Tensors

In [174]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [175]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [176]:
xT = tf.transpose(x)
print(xT)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [177]:
xT = tf.transpose(x, perm=[1,0])
print(xT)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
